### ISSUE TITLE
clean references to linked frameworks

### ISSUE THREAD

**Issue by jessefulton** [YCAMInterlab/ProCamToolkit#10]
I'm brand new to XCode & OF, so apologies if any of this is unclear...

On a clean checkout of the project, most of the references in mapamok.xcodeproj are broken. It looks like something was setup with an absolute path in the project and it's trying to find various things in `/Users/kyle/Documents/openFrameworks/`

I've downloaded the app to my  `of_preRelease_v007_osx/apps` directory and have installed all of the dependencies (ofxControlPanel, ofxOpenCv, etc.) After re-linking everything and resolving some of the path issues, I'm still getting errors building mapamok. From the error log, it seems like a few directories are still stuck looking for Kyle's directory structure, and it also seems to be looking for various (unused?) libraries under ofxOpenCV such as iphone, android, etc... When I build, I get a handful of warnings followed by the error:

Undefined symbols for architecture i386:
  "cv::Rodrigues(cv::Mat const&, cv::Mat&)", referenced from:
      ofxCv::makeMatrix(cv::Mat, cv::Mat) in Helpers.o

At this point, I'm not familiar enough with XCode to see why these errors keep occurring. (I vaguely remember something similar happening with another OF project - something to do with 32-bit vs 64-bit?)

Full log here: https://gist.github.com/2013918

FWIW I'm using XCode 4.2 on Snow Leopard.

**Comment by kylemcdonald** [comment]
i'm still using xcode 3, and i know xcode 4 isn't very smart about xcode 3 projects.

that said, the kyle/ paths are wrong. sometimes i see absolute paths in my project files even when i explicitly tell it 'relative'.

i'll try rebuilding it for you. you will probably still have to switch the base sdk from 10.7 or 'auto' to 10.6.

**Comment by kylemcdonald** [comment]
can you try 71ceaf60681f141319d7a3ffb2b86984d1107fd9

**Comment by jessefulton** [comment]
Got it running now! That let me compile and run _but_ first I had to modify testApp.cpp:setupControlPanel and change:

```
panel.addMultiToggle("drawMode", 3, variadic("faces")("fullWireframe")("outlineWireframe")("occludedWireframe"));
panel.addMultiToggle("shading", 0, variadic("none")("lights")("shader"));
```

to this: 

```
panel.addMultiToggle("drawMode", "drawMode", 3, variadic("faces")("fullWireframe")("outlineWireframe")("occludedWireframe"));
panel.addMultiToggle("shading", "shading", 0, variadic("none")("lights")("shader"));
```

Error was: method expects 4 params, not 3 (I'm using latest version of ofxControlPanel from github)

Also, there's no default model file included, so I just copied over the one from the "release" download into the data folder.

Thanks!
