### ISSUE TITLE
Cant' run or open mapamok

### ISSUE THREAD

**Issue by ogthugs** [YCAMInterlab/ProCamToolkit#11]
Hi,
I'm trying to compile the app but i cannot make it happen. This is what i get:

install_name_tool: can't open file: /Users/ogthugs/Documents/OF7Temp/addons/ProCamToolkit/mapamok/bin//mapamokDebug.app/Contents/MacOS/mapamokDebug (No such file or directory)
Command /bin/sh failed with exit code 1

I also would like to play around with the app, and i don't see the app in the ZIP file or in your code. I can't imagine the app being in there since the ZIP file only has 255KB. 

It would great if you could help me out.
thanks

**Comment by kylemcdonald** [comment]
hey! there could be a number of problems with your compilation process. unfortunately that's a really ambiguous error message.

but regarding the .zip file, please try downloading it again. i just checked and it works fine. you should get an 11MB file after unzipping.
