### ISSUE TITLE
I can't find the "mapamok.app" or "model.dae" files. 

### ISSUE THREAD

**Issue by Johnnythaitran** [YCAMInterlab/ProCamToolkit#9]
Hi,

I have downloaded the Mapamok zip folder, but I can not seem to find the mapamok.app or model.dae file. However, I do see the shader.frag and shader.vert files in mapamok > bin > data. Can someone please help?

I am using Mac OSX 10.6.8.

Thanks,

Johnny
Johnnythaitran@gmail.com

**Comment by kylemcdonald** [comment]
they should definitely be there. i just re-downloaded it myself (also on 10.6.8) and checked.

can you post a screenshot of what things look like immediately after you've unzipped them?

**Comment by johnnythaitran** [comment]
I re-downloaded the file and it is working now. Thanks

**Comment by johnnythaitran** [comment]
I re-downloaded the file and it is working now. Thanks.
Here's what it looked like before.
On Tue, Mar 6, 2012 at 9:12 AM, Kyle McDonald <
reply@reply.github.com
